/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Material from "./Material";

export default function Model(props) {
  const { nodes } = useGLTF("/models/hologram/car.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.interior003.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_1.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_2.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_3.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_4.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_5.geometry}>
        <Material />
      </mesh>
      <mesh geometry={nodes.interior003_6.geometry}>
        <Material />
      </mesh>
    </group>
  );
}

useGLTF.preload("/car.glb");
