/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Material from "./Material";

export default function Model(props) {
  const { nodes } = useGLTF("/models/hologram/coin.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.coin.geometry}
        // material={<Material />}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <Material />
      </mesh>
    </group>
  );
}

useGLTF.preload("/coin.gltf");
